#cloud-config
package_upgrade: all

# Install additional packages on first boot
packages:
  - htop
  - sysstat
  - iotop

# Final_message written to log when cloud-init processes are finished
final_message: "System boot (via cloud-init) is COMPLETE, after $UPTIME seconds. Finished at $TIMESTAMP"
