---

- name: Create virtualenv and update pip
  pip: name=pip virtualenv={{virtual_env}}

- name: install dependencies into virtualenv
  action: pip name={{item}}  virtualenv={{virtual_env}} state=present
  with_items:
    - matplotlib
    - numpy
    - pandas
    - pymysql
    - scikit-learn
    - scipy
    - sqlalchemy
