---

- name: create virtualenv and update pip
  become: yes
  become_user: ec2-user
  pip: name=pip virtualenv={{virtual_env}} extra_args="--upgrade"

- name: install packages into virtualenv
  become: yes
  become_user: ec2-user
  action: pip name={{item}}  virtualenv={{virtual_env}} state=present
  with_items: # These are fed into the {{item}} one at a time so the order is important SciPy must come before scikit-learn
    - numpy
    - matplotlib
    - pandas
    - scipy
    - scikit-learn
    - pymysql
    - sqlalchemy
    - ipython
